services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri_sight_backend
    env_file: .env
    ports:
      - "8005:8005"
    depends_on:
      - db
    volumes:
      - nutri_sight_data_volume:/app/data
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: nutri_sight_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-food_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-food_pass}
      POSTGRES_DB: ${POSTGRES_DB:-food_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  nutri_sight_data_volume:
  postgres_data:
